Repository mozilla/notes, pull requests merged in 2018-02, with the labels that each got.

#619 Preparing 2.2.0 release
  .eslintrc.yml
  CHANGELOG.md
  docs/issue_template.md
  docs/metrics.md
  locales/ar/notes.properties
  locales/az/notes.properties
  locales/bs/notes.properties
  locales/cak/notes.properties
  locales/cs/notes.properties
  locales/de/notes.properties
  locales/dsb/notes.properties
  locales/en-US/notes.properties
  locales/es-AR/notes.properties
  locales/es-CL/notes.properties
  locales/es-ES/notes.properties
  locales/es-MX/notes.properties
  locales/fa/notes.properties
  locales/fr/notes.properties
  locales/fy-NL/notes.properties
  locales/hi-IN/notes.properties
  locales/hsb/notes.properties
  locales/hu/notes.properties
  locales/it/notes.properties
  locales/ja/notes.properties
  locales/ka/notes.properties
  locales/kab/notes.properties
  locales/ko/notes.properties
  locales/ms/notes.properties
  locales/nb-NO/notes.properties
  locales/nl/notes.properties
  locales/nn-NO/notes.properties
  locales/pt-BR/notes.properties
  locales/pt-PT/notes.properties
  locales/ro/notes.properties
  locales/ru/notes.properties
  locales/sk/notes.properties
  locales/sl/notes.properties
  locales/sv-SE/notes.properties
  locales/tl/notes.properties
  locales/tr/notes.properties
  locales/zh-CN/notes.properties
  locales/zh-TW/notes.properties
  package.json
  src/background.js
  src/fxa-utils.js
  src/manifest.json
  src/settings/settings.js
  src/sidebar/editor.js
  src/sidebar/migration.js
  src/sidebar/panel.js
  src/sidebar/styles-dark.css
  src/sidebar/styles.css
  src/sidebar/theme.js
  src/sync.js
Labels: ckeditor

#550 Moving code base to React
  .babelrc
  .eslintrc.yml
  .travis.yml
  package-lock.json
  package.json
  src/background.js
  src/manifest.json
  src/settings/settings.css
  src/settings/settings.js
  src/sidebar/app/app.js
  src/sidebar/app/components/Footer.js
  src/sidebar/app/components/Panel.js
  src/sidebar/app/components/editor/Editor.js
  src/sidebar/app/components/editor/data/config.js
  src/sidebar/app/components/editor/data/initialContent.js
  src/sidebar/app/components/icons/FeedbackIcon.js
  src/sidebar/app/components/icons/SyncIcon.js
  src/sidebar/app/constants.js
  src/sidebar/app/editor.js
  src/sidebar/app/theme.js
  src/sidebar/app/utils.js
  src/sidebar/index.html
  src/sidebar/migration.js
  src/sidebar/panel.html
  src/sidebar/panel.js
  src/sidebar/static/css/styles-dark.css
  src/sidebar/static/scss/ckeditor.scss
  src/sidebar/static/scss/footer.scss
  src/sidebar/static/scss/menu.scss
  src/sidebar/static/scss/styles.scss
  src/sidebar/static/svg/close.svg
  src/sidebar/static/svg/three-dots-dark.svg
  src/sidebar/static/svg/three-dots.svg
  src/sidebar/styles.css
  src/sync.js
  webpack.config.js
Labels: Multiple Notes

#687 Change sync text to black in footer
  package-lock.json
  src/sidebar/app/components/Footer.js
  src/sidebar/static/css/styles-dark.css
  src/sidebar/static/scss/footer.scss
Labels: React.js move

#655 'Send to Notes' context menu
  docs/metrics.md
  locales/en-US/notes.properties
  src/background.js
  src/manifest.json
  src/sidebar/app/components/editor/Editor.js
Labels: React.js move

#706 Fix broken max line limit in react version
  src/sidebar/app/components/CloseIcon.js
  src/sidebar/app/components/Editor.js
  src/sidebar/static/scss/ckeditor.scss
  src/sidebar/static/scss/styles.scss
Labels: React.js move

#697 Preparing 3.0.0 release
  CHANGELOG.md
  package-lock.json
  package.json
  src/manifest.json
Labels: React.js move
